services:
  web_client:
    build:
      context: .
    container_name: web_client
    ports:
      - "3000:3000"
    # 개발 환경에서만 사용하고, 배포 환경에서는 아래 볼륨 마운트를 제거하거나 주석 처리하세요
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    stdin_open: true
    tty: true
    networks:
      - dokalab_blog_network
    
networks:
  dokalab_blog_network:
    external: true